### ISSUE TITLE
Allow empty credentials/other authentication methods

### ISSUE THREAD

**Issue by unusual-aspect** [Trigus42/alpine-qbittorrentvpn#15]
I have private VPN hosting, that i manage vpn files/configs - and as part of: 'i don't care about logins' - i create palin vpn config that is not requires to have any logins.

This also can be used for some free vpns - as they not always provide username/passwd and only give ovpn file.

So i end up with:
2022-01-31 09:04:56 [ERROR] No credentials set and didn't find a credential config file.

And all other connection sequences are terminated. 
It will be nice to try to use ovpn file without - and if failed to use - then try to look for credentials, and as lst one failed if unable to login

**Comment by Trigus42** [comment]
https://github.com/Trigus42/alpine-qbittorrentvpn/commit/37b9b336e30e5ea8410f6006245b0c3e3105b801 adds support for empty credentials. For example:
```yml
version: "3.3"

services:
  qbittorrent:
    image: trigus42/qbittorrentvpn
    container_name: qbittorrent
    environment:
      - VPN_ENABLED=yes
      - VPN_TYPE=openvpn
      - VPN_USERNAME=
      - VPN_PASSWORD=
      - LAN_NETWORK=192.168.0.0/24
      - ENABLE_SSL=yes
    volumes:
      - './config/:/config'
    ports:
      - 80:8080
      - 443:8080
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
```

You can also add an empty [credentials file](https://github.com/Trigus42/alpine-qbittorrentvpn#how-to-use-openvpn).
