### ISSUE TITLE
Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by mechabubba** [Trigus42/alpine-qbittorrentvpn#29]
hello there,

having an issue connecting to my clients web ui. attempting to connect to it from outside the container results in the following;
```sh
# on local machine...
$ curl localhost:8080
curl: (56) Recv failure: Connection reset by peer

# on a remote machine its the same story.
```
i am using image `trigus42/qbittorrentvpn:qbt4.5.2` with wireguard. i don't have any other firewalls like ufw installed yet. my system is a **raspberry pi 4**, running **raspbian bullseye arm64 lite**.

<details>
<summary>docker-compose.yml</summary>

```yaml
version: "3.3"
services:
  qbittorrent:
    image: trigus42/qbittorrentvpn:qbt4.5.2
    container_name: qbittorrent
    privileged: true
    ports:
      - 8080:8080
      - 8999:8999
    volumes:
      - /home/torrents/.config/:/config
      - /media/data/Torrents/:/downloads
    environment:
      - VPN_ENABLED=yes
      - VPN_TYPE=wireguard
      - LAN_NETWORK=10.0.0.0/24
      - PGID=1001
      - PUID=1001
      - SET_FWMARK=yes
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    sysctls:
      # - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
```
</details><details>
<summary>log</summary>

```
qbittorrent  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
qbittorrent  | [s6-init] ensuring user provided files have correct perms...exited 0.
qbittorrent  | [fix-attrs.d] applying ownership & permissions fixes...
qbittorrent  | [fix-attrs.d] done.
qbittorrent  | [cont-init.d] executing container initialization scripts...
qbittorrent  | [cont-init.d] 01-environment.sh: executing...
qbittorrent  | 2023-06-03 14:33:22 [INFO] LAN_NETWORK defined as '10.0.0.0/24'
qbittorrent  | 2023-06-03 14:33:22 [INFO] Docker network defined as 172.18.0.0/16
qbittorrent  | 2023-06-03 14:33:22 [INFO] PUID defined as 1001
qbittorrent  | 2023-06-03 14:33:22 [INFO] PGID defined as 1001
qbittorrent  | 2023-06-03 14:33:22 [INFO] An user with PUID 1001 already existsin /etc/passwd, nothing to do.
qbittorrent  | 2023-06-03 14:33:22 [INFO] VPN_ENABLED defined as 'yes'
qbittorrent  | 2023-06-03 14:33:22 [INFO] VPN_TYPE defined as 'wireguard'
qbittorrent  | 2023-06-03 14:33:22 [WARNING] NAME_SERVERS not defined (via -e NAME_SERVERS), defaulting to CloudFlare and Google name servers
qbittorrent  | 2023-06-03 14:33:22 [INFO] Adding 1.1.1.1 to resolv.conf
qbittorrent  | 2023-06-03 14:33:22 [INFO] Adding 8.8.8.8 to resolv.conf
qbittorrent  | 2023-06-03 14:33:22 [INFO] Adding 1.0.0.1 to resolv.conf
qbittorrent  | 2023-06-03 14:33:22 [INFO] Adding 8.8.4.4 to resolv.conf
qbittorrent  | [cont-init.d] 01-environment.sh: exited 0.
qbittorrent  | [cont-init.d] 02-vpn.sh: executing...
qbittorrent  | 2023-06-03 14:33:22 [INFO] Choosen VPN config: 'vpn_config.conf'
qbittorrent  | dos2unix: converting file /config/wireguard/vpn_config.conf to Unix format...
qbittorrent  | 2023-06-03 14:33:22 [INFO] VPN remote line defined as 'XXX.XX.XXX.XX:51820'
qbittorrent  | 2023-06-03 14:33:22 [INFO] VPN_REMOTE defined as 'XXX.XX.XXX.XX'
qbittorrent  | 2023-06-03 14:33:22 [INFO] VPN_PORT defined as '51820'
qbittorrent  | 2023-06-03 14:33:22 [INFO] VPN_PROTOCOL set as 'udp', since WireGuard is always udp.
qbittorrent  | 2023-06-03 14:33:22 [INFO] VPN_DEVICE_TYPE set as 'vpn_config'
qbittorrent  | 2023-06-03 14:33:22 [INFO] Starting WireGuard...
qbittorrent  | --------------------
qbittorrent  | Warning: `/config/wireguard/vpn_config.conf' is world accessible
qbittorrent  | [#] ip link add vpn_config type wireguard
qbittorrent  | [#] wg setconf vpn_config /dev/fd/63
qbittorrent  | [#] ip -4 address add 10.67.25.43/32 dev vpn_config
qbittorrent  | [#] ip link set mtu 1420 up dev vpn_config
qbittorrent  | [#] resolvconf -a vpn_config -m 0 -x
qbittorrent  | [#] wg set vpn_config fwmark 51820
qbittorrent  | [#] ip -4 route add 0.0.0.0/0 dev vpn_config table 51820
qbittorrent  | [#] ip -4 rule add not fwmark 51820 table 51820
qbittorrent  | [#] ip -4 rule add table main suppress_prefixlength 0
qbittorrent  | [#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
qbittorrent  | [#] iptables-restore -n
qbittorrent  | --------------------
qbittorrent  | [cont-init.d] 02-vpn.sh: exited 0.
qbittorrent  | [cont-init.d] 03-network.sh: executing...
qbittorrent  | 2023-06-03 14:33:22 [INFO] Adding 10.0.0.0/24 as route via docker eth0
qbittorrent  | 2023-06-03 14:33:22 [INFO] Adding fwmark for webui.
qbittorrent  | [cont-init.d] 03-network.sh: exited 0.
qbittorrent  | [cont-init.d] 04-qbittorrent-setup.sh: executing...
qbittorrent  | 2023-06-03 14:33:23 [WARNING] ENABLE_SSL is set to , SSL is not enabled. This could cause issues with logging if other apps use the same Cookie name (SID).
qbittorrent  | 2023-06-03 14:33:23 [WARNING] If you manage the SSL config yourself, you can ignore this.
qbittorrent  | 2023-06-03 14:33:23 [WARNING] UMASK not defined (via -e UMASK), defaulting to '002'
qbittorrent  | [cont-init.d] 04-qbittorrent-setup.sh: exited 0.
qbittorrent  | [cont-init.d] 05-install.sh: executing...
qbittorrent  | [cont-init.d] 05-install.sh: exited 0.
qbittorrent  | [cont-init.d] done.
qbittorrent  | [services.d] starting services
qbittorrent  | 2023-06-03 14:33:23 [INFO] Logging to /config/qBittorrent/data/logs/qbittorrent.log.
qbittorrent  | [services.d] done.
qbittorrent  | 2023-06-03 14:33:23 [INFO] Trying to ping 1.1.1.1 and 8.8.8.8 over the docker interface for 500ms each...
qbittorrent  | Terminated
qbittorrent  | Terminated
qbittorrent  | 2023-06-03 14:33:25 [INFO] Success: Could not connect. This means the firewall is most likely working properly.
qbittorrent  | 2023-06-03 14:33:25 [INFO] qBittorrent started with PID 539
qbittorrent  | 2023-06-03 14:33:25 [INFO] HEALTH_CHECK_HOST is not set. Using default host one.one.one.one
qbittorrent  | 2023-06-03 14:33:25 [INFO] HEALTH_CHECK_INTERVAL is not set. Using default interval of 5s
```
</details>

i am fairly new to using docker and many aspects of networking, so hopefully this isn't a newbie issue (i have a irc bouncer set up here too via docker, and i have no problems connecting to that...). let me know if i can provide any other information. thanks.
