### ISSUE TITLE
WebUI not connecting

### ISSUE THREAD

**Issue by leelouch** [Trigus42/alpine-qbittorrentvpn#66]
Hi, 
could you please help me identifiying what is going on ?
I am unable to connect to qbit webui, 

- **if vpn is disabled all ok** 
- when vpn is up: 
-- vpn is up and internet connection is ok  (wget on google.com)
-- I am unable to ping my pc from the docker ( ping 192.168.0.10 ) 
-- I am unable to access the webui from the pc

in the log I found some errors , I don't know if it is related : 
```
alpine-qbittorrent    | Error: Could not process rule: No such file or directory
alpine-qbittorrent    | add chain inet qbt-mark output { type route hook output priority -150 ; }
alpine-qbittorrent    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
alpine-qbittorrent    | Error: Could not process rule: No such file or directory
alpine-qbittorrent    | add rule inet qbt-mark output ct mark 9090 meta mark set 8080 counter comment "Add mark to outgoing packets belonging to a WebUI connection"
alpine-qbittorrent    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^**
```

docker compose : 
```
version: '3.3'
services:
    alpine-qbittorrent:
        container_name: alpine-qbittorrent
        cap_add:
            - NET_ADMIN
        volumes:
            - '/volume1/video/:/downloads'
            - '/volume1/:/volume1'
            - '-----------------/config:/config'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - VPN_ENABLED=yes
            - VPN_TYPE=openvpn
            - LOCAL_NETWORK=192.168.0.0/16
            - WEBUI_ALLOWED_NETWORKS=0.0.0.0
            - DOWNLOAD_DIR_CHOWN=no
            - BIND_INTERFACE=yes
            - VPN_USERNAME=--------------------
            - VPN_PASSWORD=-------------------
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '8080:8080'
            - '6881:6881'
            - '6881:6881/udp'
            - '8118:8118'
        image: trigus42/qbittorrentvpn
        restart: unless-stopped
```

- My PC ip : 192.168.0.10
- Odroid linux IP : 192.168.0.102
  -- linux is listinning to port 8080 : `tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN`

[qbittorrent log.txt](https://github.com/Trigus42/alpine-qbittorrentvpn/files/15214498/qbittorrent.log.txt)
[docker-logs-alpine.txt](https://github.com/Trigus42/alpine-qbittorrentvpn/files/15225583/docker-logs-alpine.txt)

docker bash : 
```
/ # netstat -na
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 127.0.0.11:38475        0.0.0.0:*               LISTEN
tcp        0      0 172.19.0.2:13455        0.0.0.0:*               LISTEN
tcp        0      0 10.100.0.2:13455        0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:13455         0.0.0.0:*               LISTEN
tcp        0      0 172.19.0.2:59866        82.102.19.137:443       ESTABLISHED
tcp6       0      0 :::8080                 :::*                    LISTEN
udp        0      0 0.0.0.0:6771            0.0.0.0:*
udp        0      0 0.0.0.0:6771            0.0.0.0:*
udp        0      0 0.0.0.0:6771            0.0.0.0:*
udp        0      0 127.0.0.11:56424        0.0.0.0:*
udp        0      0 172.19.0.2:13455        0.0.0.0:*
udp        0      0 10.100.0.2:13455        0.0.0.0:*
udp        0      0 127.0.0.1:13455         0.0.0.0:*
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ACC ]     STREAM     LISTENING     1847243  /config/qBittorrent/config/.mKtOZs/s
```

ifconfig: 
```
/ # ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.19.0.2  netmask 255.255.0.0  broadcast 172.19.255.255
        ether 02:42:ac:13:00:02  txqueuelen 0  (Ethernet)
        RX packets 355  bytes 75925 (74.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 307  bytes 56791 (55.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.100.0.2  netmask 255.255.255.0  destination 10.100.0.2
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 183  bytes 40786 (39.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 238  bytes 28285 (27.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
```
on docker : 
/ # route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.100.0.1      128.0.0.0       UG    0      0        0 tun0
default         172.19.0.1      0.0.0.0         UG    0      0        0 eth0
10.100.0.0      *               255.255.255.0   U     0      0        0 tun0
82.102.19.137   172.19.0.1      255.255.255.255 UGH   0      0        0 eth0
128.0.0.0       10.100.0.1      128.0.0.0       UG    0      0        0 tun0
172.19.0.0      *               255.255.0.0     U     0      0        0 eth0

```
**http://192.168.0.102:8080/**:

![image](https://github.com/Trigus42/alpine-qbittorrentvpn/assets/9366148/8f8b2bc1-509e-4d30-a88a-888643b5f608)
